### ISSUE TITLE
dora collect SIGSEGV due to error on metrics

### ISSUE THREAD

**Issue by lero** [bmc-toolbox/dora#10]
```
$ sudo dora collect xxxxx
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xcc5071]

goroutine 97 [running]:
github.com/bmc-toolbox/dora/vendor/github.com/bmc-toolbox/gin-go-metrics.IncrCounter(...)
	/builddir/build/BUILD/dora-2.3.9/GO/src/github.com/bmc-toolbox/dora/vendor/github.com/bmc-toolbox/gin-go-metrics/metrics.go:160
github.com/bmc-toolbox/dora/connectors.collect(0xc0000b89c0, 0xc0000a3f80, 0xc00011c370)
	/builddir/build/BUILD/dora-2.3.9/GO/src/github.com/bmc-toolbox/dora/connectors/collection.go:121 +0xc01
github.com/bmc-toolbox/dora/connectors.DataCollection.func1(0xc0000b89c0, 0xc0000a3f80, 0xc00011c370, 0xc0003a6cc0)
	/builddir/build/BUILD/dora-2.3.9/GO/src/github.com/bmc-toolbox/dora/connectors/collection.go:138 +0x65
created by github.com/bmc-toolbox/dora/connectors.DataCollection
	/builddir/build/BUILD/dora-2.3.9/GO/src/github.com/bmc-toolbox/dora/connectors/collection.go:136 +0x169
```

**Comment by paskal** [comment]
I'll look into it, seems like setup step was not done before code tries to write some metric.

**Comment by paskal** [comment]
v2.3.10 should fix the problem, please check.
